#!/usr/bin/expect
# October 14 2017
# Ardavan Hashemzadeh
# Test logging function
proc log {message \
        {port 12345} \
        {server logs.papertrailapp.com} \
        {logfile ioti.log}} {
  exec logger "$message" -n $server -P $port -t IoTi
  exec /bin/bash -c "echo `date` $message >> $logfile"
}
log [lindex $argv 0]
