#!/usr/bin/expect
# October 13 2017
# Ardavan Hashemzadeh
# Test logging function

proc log {message \
        {port 12345} \
        {server logs.papertrailapp.com} \
        {logfile ioti.log} \
        {tag IoTi}} {
  exec logger "$message" -n $server -P $port -t $tag
  exec /bin/bash -c "echo `date` $message >> $logfile"
}

log [lindex $argv 0]
